# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: containers.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto


@dataclass
class RContainers(betterproto.Message):
    """type = 'r-containers'origin = server"""

    containers: Dict[str, "RContainer"] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )


@dataclass
class ScanRContainer(betterproto.Message):
    """type = 'scan-r-container'origin = client"""

    nfc_id: str = betterproto.string_field(1)


@dataclass
class ScannedRContainer(betterproto.Message):
    """type = 'scanned-r-container'origin = server"""

    nfc_id: str = betterproto.string_field(1)
    date_created: int = betterproto.uint64_field(2)


@dataclass
class LoadRContainerInfo(betterproto.Message):
    """type = 'load-r-container-info'origin = client"""

    nfc_id: str = betterproto.string_field(1)


@dataclass
class RContainerInfo(betterproto.Message):
    """type = 'r-container-info'origin = server"""

    nfc_id: str = betterproto.string_field(1)
    origin_seller: str = betterproto.string_field(2)
    origin_location: str = betterproto.string_field(3)
    food_g: int = betterproto.int32_field(4)
    waste_saved_g: int = betterproto.int32_field(5)
    co2_saved_g: int = betterproto.int32_field(6)
    mass: List["TimePoint"] = betterproto.message_field(7)
    co2: List["TimePoint"] = betterproto.message_field(8)
    waste: List["TimePoint"] = betterproto.message_field(9)
    purchases: List["Purchase"] = betterproto.message_field(10)


@dataclass
class RContainer(betterproto.Message):
    nfc_id: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    date_created: int = betterproto.uint64_field(3)


@dataclass
class TimePoint(betterproto.Message):
    time: int = betterproto.uint64_field(1)
    value: float = betterproto.float_field(2)


@dataclass
class Purchase(betterproto.Message):
    date: int = betterproto.uint64_field(1)
    item: str = betterproto.string_field(2)
    weight_g: int = betterproto.int32_field(3)
