# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: form_errors.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto


@dataclass
class FormErrors(betterproto.Message):
    """type = 'form-errors'origin = server"""

    related_message_type: str = betterproto.string_field(1)
    errors: Dict[str, "SList"] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )


@dataclass
class SList(betterproto.Message):
    list: List[str] = betterproto.string_field(1)
