# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: rewards.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class LoadRewards(betterproto.Message):
    """type = 'load-rewards'origin = client"""

    nfc_ids: List[str] = betterproto.string_field(1)


@dataclass
class Rewards(betterproto.Message):
    """type = 'rewards'origin = serverclient cache = years(1)"""

    rewards: List["Reward"] = betterproto.message_field(1)


@dataclass
class Reward(betterproto.Message):
    reason: str = betterproto.string_field(1)
    reward: str = betterproto.string_field(2)
