# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: scale.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ScaleUpdate(betterproto.Message):
    """type = 'scale-update'origin = server"""

    nfc_id: str = betterproto.string_field(1)
    weight_g: float = betterproto.double_field(2)


@dataclass
class ScaleMeasurement(betterproto.Message):
    """type = 'scale-measurement'origin = client"""

    nfc_id: str = betterproto.string_field(1)
    weight_g: int = betterproto.int32_field(2)
