# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: sfiles.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class UploadStartSlot(betterproto.Message):
    """
    type = 'upload-start'origin = serverclient cache = days(7)client cache_keys
    = text('local_key')
    """

    key: str = betterproto.string_field(1)
    local_key: str = betterproto.string_field(2)


@dataclass
class UploadProgress(betterproto.Message):
    """type = 'upload-progress'origin = server"""

    n_bytes: int = betterproto.int64_field(1)
    key: str = betterproto.string_field(2)
    local_key: str = betterproto.string_field(3)


@dataclass
class UploadDone(betterproto.Message):
    """type = 'upload-done'origin = server"""

    key: str = betterproto.string_field(1)
    file: "UploadedFile" = betterproto.message_field(2)


@dataclass
class UploadedFile(betterproto.Message):
    local_key: str = betterproto.string_field(1)
    url: str = betterproto.string_field(2)
    id: str = betterproto.string_field(3)
    mime: str = betterproto.string_field(4)
    thumb_url: str = betterproto.string_field(5)
    name: str = betterproto.string_field(6)
    downloadable: bool = betterproto.bool_field(7)


@dataclass
class UploadStart(betterproto.Message):
    """
    type = 'upload-start'origin = clientclient cache = years(1)client
    cache_keys = text('local_key')
    """

    local_key: str = betterproto.string_field(1)
    extension: str = betterproto.string_field(2)
    name: str = betterproto.string_field(3)
    mime: str = betterproto.string_field(4)


@dataclass
class DeleteFile(betterproto.Message):
    """type = 'delete-file'origin = client"""

    file: "UploadedFile" = betterproto.message_field(1)


@dataclass
class UploadEnd(betterproto.Message):
    """type = 'upload-end'origin = client"""

    pass
