# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: uploader.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto


class UploadStatus(betterproto.Enum):
    scheduled = 0
    uploading = 1
    paused = 3
    done = 4
    error = 5
    restored = 6


@dataclass
class UploadTask(betterproto.Message):
    """
    type = 'upload-task'origin = serverclient cache = years(1)client cache_keys
    = text('fingerprint')
    """

    created: int = betterproto.uint64_field(1)
    path: str = betterproto.string_field(2)
    name: str = betterproto.string_field(3)
    mime: str = betterproto.string_field(4)
    status: "UploadStatus" = betterproto.enum_field(5)
    retry_counter: int = betterproto.int32_field(6)
    error: str = betterproto.string_field(7)
    fingerprint: str = betterproto.string_field(8)
    url: str = betterproto.string_field(9)
    metadata: Dict[str, str] = betterproto.map_field(
        10, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
