# Generated by Django 3.1.7 on 2021-05-22 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RContainer',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=64, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('nfc_id', models.CharField(max_length=255, unique=True)),
                ('weight_sum_g', models.IntegerField(default=0)),
                ('origin_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.seller')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='ContainerPurchase',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=64, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('weight_g', models.IntegerField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containers.rcontainer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.product')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
