# Generated by Django 3.1.7 on 2021-05-22 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=64, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('reward', models.CharField(max_length=255)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containers.rcontainer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
